# Generated by Django 5.1.4 on 2025-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "header",
                    models.CharField(
                        help_text="Введите заголовок блога", max_length=150, verbose_name="Заголовок блога"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Введите содержание блога", null=True, verbose_name="Содержание блога"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью блога",
                        null=True,
                        upload_to="blogs/photo",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Отметьте, если блог опубликован", verbose_name="Опубликовано"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Введите количество просмотров", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
